//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklisthistoricocivilitem
    {
        public long autonumero { get; set; }
        public Nullable<long> autonumeroHistoricoCivil { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string anoMes { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public string nomeSubSistema { get; set; }
        public Nullable<int> autonumeroPredio { get; set; }
        public string nomePredio { get; set; }
        public Nullable<int> autonumeroSetor { get; set; }
        public string item { get; set; }
        public string nome { get; set; }
        public string d { get; set; }
        public string e { get; set; }
        public string q { get; set; }
        public string m { get; set; }
        public string b { get; set; }
        public string t { get; set; }
        public string s { get; set; }
        public string a { get; set; }
        public string executou { get; set; }
        public Nullable<int> autonumeroLocal { get; set; }
        public string nomeLocal { get; set; }
    }
}
