//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklistveiculo
    {
        public int autonumero { get; set; }
        public Nullable<short> item { get; set; }
        public string nome { get; set; }
        public Nullable<bool> sim { get; set; }
        public Nullable<bool> nao { get; set; }
        public Nullable<bool> avariado { get; set; }
        public string grupo { get; set; }
    }
}
