//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklisthistitemnrofolha
    {
        public int autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string anoMes { get; set; }
        public Nullable<int> autonumeroCheckList { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public Nullable<long> contadorPmocEquipamento { get; set; }
        public string item { get; set; }
        public string nome { get; set; }
        public string d { get; set; }
        public string e { get; set; }
        public string q { get; set; }
        public string m { get; set; }
        public string b { get; set; }
        public string t { get; set; }
        public string s { get; set; }
        public string a { get; set; }
        public string equip1 { get; set; }
        public string equip2 { get; set; }
        public string equip3 { get; set; }
        public string equip4 { get; set; }
        public string equip5 { get; set; }
        public string equip6 { get; set; }
        public string equip7 { get; set; }
        public string equip8 { get; set; }
    }
}
