//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklisthistorico
    {
        public long autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string anoMes { get; set; }
        public Nullable<long> autonumeroEquipamento { get; set; }
        public string endereco { get; set; }
        public Nullable<int> autonumeroSistema { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public string nomeSubSistema { get; set; }
        public Nullable<int> autonumeroLocalFisico { get; set; }
        public string nomeLocalFisico { get; set; }
        public Nullable<int> autonumeroSetor { get; set; }
        public string nomeSetor { get; set; }
        public Nullable<int> autonumeroPredio { get; set; }
        public string nomePredio { get; set; }
        public string serie { get; set; }
        public string modelo { get; set; }
        public string capacidade { get; set; }
        public string patrimonio { get; set; }
        public Nullable<int> grupo { get; set; }
        public string fabricante { get; set; }
        public Nullable<System.DateTime> dataPrevista { get; set; }
        public string cancelado { get; set; }
        public string mesManuAno { get; set; }
        public string mesManuSemestre { get; set; }
        public Nullable<long> contadorPmocEquipamento { get; set; }
        public string obsLocal { get; set; }
        public Nullable<int> autonumeroFuncionario { get; set; }
        public string nomeFuncionario { get; set; }
        public Nullable<int> autonumeroProfissao { get; set; }
        public string nomeProfissao { get; set; }
        public Nullable<System.TimeSpan> totalHoras { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
        public string fechado { get; set; }
        public string imprimir { get; set; }
    }
}
