//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist
    {
        public int autonumero { get; set; }
        public Nullable<int> autonumeroContrato { get; set; }
        public string nomeContrato { get; set; }
        public Nullable<int> autonumeroSistema { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroSubsistema { get; set; }
        public string nomeSubSistema { get; set; }
        public string item { get; set; }
        public string nome { get; set; }
        public string d { get; set; }
        public string e { get; set; }
        public string q { get; set; }
        public string m { get; set; }
        public string b { get; set; }
        public string t { get; set; }
        public string s { get; set; }
        public string a { get; set; }
        public string cancelado { get; set; }
    }
}
