//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklisthistoriconrofolha
    {
        public long autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string anoMes { get; set; }
        public Nullable<long> contadorPmocEquipamento { get; set; }
        public Nullable<int> equip1 { get; set; }
        public Nullable<int> equip2 { get; set; }
        public Nullable<int> equip3 { get; set; }
        public Nullable<int> equip4 { get; set; }
        public Nullable<int> equip5 { get; set; }
        public Nullable<int> equip6 { get; set; }
        public Nullable<int> equip7 { get; set; }
        public Nullable<int> equip8 { get; set; }
        public Nullable<sbyte> mensal { get; set; }
        public Nullable<sbyte> bimestral { get; set; }
        public Nullable<sbyte> trimestral { get; set; }
        public Nullable<sbyte> semestral { get; set; }
        public Nullable<sbyte> anual { get; set; }
    }
}
