//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratofuncionario
    {
        public int autonumero { get; set; }
        public Nullable<int> autonumeroContrato { get; set; }
        public string nomeContrato { get; set; }
        public Nullable<int> autonumeroFuncionario { get; set; }
        public string nomeFuncionario { get; set; }
        public string cancelado { get; set; }
    }
}
