//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipamentodefeito
    {
        public int autonumero { get; set; }
        public Nullable<long> autonumeroEquipamento { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFim { get; set; }
        public Nullable<decimal> totalHorasFuncionando { get; set; }
        public Nullable<long> totalSegundosFuncionando { get; set; }
        public Nullable<decimal> totalHorasParado { get; set; }
        public Nullable<long> totalSegundosParado { get; set; }
        public string cancelado { get; set; }
    }
}
