//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public int autonumero { get; set; }
        public Nullable<int> autonumeroProfissao { get; set; }
        public string nomeProfissao { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string matricula { get; set; }
        public Nullable<decimal> salario { get; set; }
        public Nullable<System.DateTime> dataSaida { get; set; }
        public Nullable<System.DateTime> dataEntrada { get; set; }
        public string obs { get; set; }
        public Nullable<int> autonumeroContrato { get; set; }
        public string nomeContrato { get; set; }
        public string cancelado { get; set; }
        public string cpf { get; set; }
    }
}
