//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicao
    {
        public long autonumero { get; set; }
        public Nullable<int> autonumeroUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public string id { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public Nullable<int> autonumeroLocalAtendido { get; set; }
        public string nomeLocalAtendido { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public Nullable<decimal> umidade { get; set; }
        public string cancelado { get; set; }
    }
}
