//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class manutEntities : DbContext
    {
        public manutEntities()
            : base("name=manutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_prioridade> tb_prioridade { get; set; }
        public DbSet<tb_status_os> tb_status_os { get; set; }
        public DbSet<tb_tipo_servico> tb_tipo_servico { get; set; }
        public DbSet<tb_tipo_usuario> tb_tipo_usuario { get; set; }
        public DbSet<tb_os_acompanhamento> tb_os_acompanhamento { get; set; }
        public DbSet<tb_predio> tb_predio { get; set; }
        public DbSet<tb_local> tb_local { get; set; }
        public DbSet<tb_preventiva> tb_preventiva { get; set; }
        public DbSet<tb_feriado> tb_feriado { get; set; }
        public DbSet<tb_equipe> tb_equipe { get; set; }
        public DbSet<tb_etapa> tb_etapa { get; set; }
        public DbSet<tb_local_fisico> tb_local_fisico { get; set; }
        public DbSet<tb_setor> tb_setor { get; set; }
        public DbSet<tb_anexo> tb_anexo { get; set; }
        public DbSet<tb_local_atendido> tb_local_atendido { get; set; }
        public DbSet<tb_situacaoordemservico> tb_situacaoordemservico { get; set; }
        public DbSet<tb_ata> tb_ata { get; set; }
        public DbSet<tb_diarioplantao> tb_diarioplantao { get; set; }
        public DbSet<tb_categoriaservico> tb_categoriaservico { get; set; }
        public DbSet<tb_ordemservico> tb_ordemservico { get; set; }
        public DbSet<grupotramitacao> grupotramitacao { get; set; }
        public DbSet<tramitacao> tramitacao { get; set; }
        public DbSet<videoaula> videoaula { get; set; }
        public DbSet<predio> predio { get; set; }
        public DbSet<setor> setor { get; set; }
        public DbSet<tb_subsistemacliente> tb_subsistemacliente { get; set; }
        public DbSet<profissao> profissao { get; set; }
        public DbSet<pmoccivilcontingencia> pmoccivilcontingencia { get; set; }
        public DbSet<pmoccivilfuncionario> pmoccivilfuncionario { get; set; }
        public DbSet<medicao> medicao { get; set; }
        public DbSet<tb_medicao> tb_medicao { get; set; }
        public DbSet<tb_medicaoitens> tb_medicaoitens { get; set; }
        public DbSet<pmocequipamentocontingencia> pmocequipamentocontingencia { get; set; }
        public DbSet<pmocequipamentofuncionario> pmocequipamentofuncionario { get; set; }
        public DbSet<contratofuncionario> contratofuncionario { get; set; }
        public DbSet<local> local { get; set; }
        public DbSet<tb_orcamento> tb_orcamento { get; set; }
        public DbSet<tb_orcamento_itens> tb_orcamento_itens { get; set; }
        public DbSet<documentocontrato> documentocontrato { get; set; }
        public DbSet<funcionariodocumento> funcionariodocumento { get; set; }
        public DbSet<profissaocurso> profissaocurso { get; set; }
        public DbSet<tb_usuario> tb_usuario { get; set; }
        public DbSet<usuariopredio> usuariopredio { get; set; }
        public DbSet<tb_funcionario> tb_funcionario { get; set; }
        public DbSet<osfuncionario> osfuncionario { get; set; }
        public DbSet<funcionario> funcionario { get; set; }
        public DbSet<funcionariocurso> funcionariocurso { get; set; }
        public DbSet<subsistemaqtdepmoc> subsistemaqtdepmoc { get; set; }
        public DbSet<tb_empresa> tb_empresa { get; set; }
        public DbSet<osfotos> osfotos { get; set; }
        public DbSet<checklist> checklist { get; set; }
        public DbSet<checklisthistitem> checklisthistitem { get; set; }
        public DbSet<checklisthistitemnrofolha> checklisthistitemnrofolha { get; set; }
        public DbSet<checklisthistoricocivil> checklisthistoricocivil { get; set; }
        public DbSet<checklisthistoricocivilitem> checklisthistoricocivilitem { get; set; }
        public DbSet<checklistveiculo> checklistveiculo { get; set; }
        public DbSet<tb_planilhafechada> tb_planilhafechada { get; set; }
        public DbSet<checklisthistorico> checklisthistorico { get; set; }
        public DbSet<checklisthistoriconrofolha> checklisthistoriconrofolha { get; set; }
        public DbSet<tb_cadastro> tb_cadastro { get; set; }
        public DbSet<tb_sistema> tb_sistema { get; set; }
        public DbSet<tb_subsistema> tb_subsistema { get; set; }
        public DbSet<tb_cliente> tb_cliente { get; set; }
        public DbSet<tb_os> tb_os { get; set; }
        public DbSet<tb_os_itens> tb_os_itens { get; set; }
        public DbSet<tb_fontes> tb_fontes { get; set; }
        public DbSet<tb_insumo> tb_insumo { get; set; }
        public DbSet<tb_servico> tb_servico { get; set; }
    }
}
