//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class osfotos
    {
        public int autonumero { get; set; }
        public Nullable<long> autonumeroOs { get; set; }
        public string codigoOs { get; set; }
        public string descricao { get; set; }
        public string url { get; set; }
        public string siglaCliente { get; set; }
    }
}
