//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmoccivilcontingencia
    {
        public int autonumero { get; set; }
        public Nullable<long> autonumeroContrato { get; set; }
        public string nomeContrato { get; set; }
        public Nullable<long> codigoPmoc { get; set; }
        public string obs { get; set; }
        public string status { get; set; }
        public string anoMes { get; set; }
        public string nomeLocal { get; set; }
        public string cancelado { get; set; }
    }
}
