//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class predio
    {
        public int autonumero { get; set; }
        public string nome { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string nomeMunicipio { get; set; }
        public string codigoMunicipioIBGE { get; set; }
        public Nullable<decimal> preventiva { get; set; }
        public Nullable<decimal> corretiva { get; set; }
        public Nullable<decimal> inspecao { get; set; }
        public string endereco { get; set; }
        public string cancelado { get; set; }
        public Nullable<long> contadorPmocCivil { get; set; }
    }
}
