//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class setor
    {
        public int autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public Nullable<int> autonumeroPredio { get; set; }
        public string nomePredio { get; set; }
        public string nome { get; set; }
        public string cancelado { get; set; }
        public Nullable<long> contadorPmocCivil { get; set; }
    }
}
