//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsistemaqtdepmoc
    {
        public long autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string anoMes { get; set; }
        public Nullable<int> autonumeroSistema { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public string nomeSubSistema { get; set; }
        public Nullable<int> mensal { get; set; }
        public Nullable<int> bimestral { get; set; }
        public Nullable<int> trimestral { get; set; }
        public Nullable<int> semestral { get; set; }
        public Nullable<int> anual { get; set; }
    }
}
