//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public int autonumero { get; set; }
        public string sigla { get; set; }
        public string nome { get; set; }
        public string contrato { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string contato { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public string cancelado { get; set; }
        public string dataBase { get; set; }
        public Nullable<double> bdiServico { get; set; }
        public Nullable<double> bdiMaterial { get; set; }
        public Nullable<long> contadorOs { get; set; }
        public Nullable<System.DateTime> dataLimite { get; set; }
        public string planilhaFechada { get; set; }
        public Nullable<int> prazoInicialMeses { get; set; }
        public Nullable<int> prorrogacoesMeses { get; set; }
        public Nullable<decimal> reducao { get; set; }
        public Nullable<long> contadorOrcamento { get; set; }
        public decimal margem { get; set; }
        public decimal qtdeCustoFixoEtapa { get; set; }
        public string obra { get; set; }
        public Nullable<long> contadorOrdemServico { get; set; }
        public string cap { get; set; }
        public string processo { get; set; }
        public string prazoInicialDias { get; set; }
        public Nullable<decimal> acrescimoEstoque { get; set; }
        public Nullable<long> contadorPmocCivil { get; set; }
        public Nullable<long> contadorPmocEquipamento { get; set; }
        public string informacoesPMOC { get; set; }
    }
}
