//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cadastro
    {
        public long autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string endereco { get; set; }
        public Nullable<int> autonumeroSistema { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public string nomeSubSistema { get; set; }
        public Nullable<int> autonumeroLocalAtendido { get; set; }
        public string nomeLocalAtendido { get; set; }
        public Nullable<int> autonumeroLocalFisico { get; set; }
        public string nomeLocalFisico { get; set; }
        public Nullable<int> autonumeroEquipe { get; set; }
        public string nomeEquipe { get; set; }
        public Nullable<int> autonumeroSetor { get; set; }
        public string nomeSetor { get; set; }
        public Nullable<int> autonumeroPredio { get; set; }
        public string nomePredio { get; set; }
        public string serie { get; set; }
        public string modelo { get; set; }
        public string capacidade { get; set; }
        public string patrimonio { get; set; }
        public Nullable<int> diaUtil { get; set; }
        public Nullable<int> grupo { get; set; }
        public string fabricante { get; set; }
        public Nullable<System.DateTime> dataPrevista { get; set; }
        public Nullable<System.DateTime> dataCompra { get; set; }
        public Nullable<System.DateTime> dataGarantia { get; set; }
        public string cancelado { get; set; }
        public Nullable<int> periodicidade { get; set; }
        public string mesManuAno { get; set; }
        public string mesManuSem01 { get; set; }
        public string mesManuSem02 { get; set; }
        public string mesManuTri01 { get; set; }
        public string mesManuTri02 { get; set; }
        public string mesManuTri03 { get; set; }
        public string mesManuTri04 { get; set; }
        public string obsLocal { get; set; }
        public string mesManuSemestre { get; set; }
        public Nullable<long> contadorPmocEquipamento { get; set; }
        public Nullable<sbyte> mes01 { get; set; }
        public Nullable<sbyte> mes02 { get; set; }
        public Nullable<sbyte> mes03 { get; set; }
        public Nullable<sbyte> mes04 { get; set; }
        public Nullable<sbyte> mes05 { get; set; }
        public Nullable<sbyte> mes06 { get; set; }
        public Nullable<sbyte> mes07 { get; set; }
        public Nullable<sbyte> mes08 { get; set; }
        public Nullable<sbyte> mes09 { get; set; }
        public Nullable<sbyte> mes10 { get; set; }
        public Nullable<sbyte> mes11 { get; set; }
        public Nullable<sbyte> mes12 { get; set; }
        public Nullable<sbyte> bim01 { get; set; }
        public Nullable<sbyte> bim02 { get; set; }
        public Nullable<sbyte> bim03 { get; set; }
        public Nullable<sbyte> bim04 { get; set; }
        public Nullable<sbyte> bim05 { get; set; }
        public Nullable<sbyte> bim06 { get; set; }
        public Nullable<sbyte> bim07 { get; set; }
        public Nullable<sbyte> bim08 { get; set; }
        public Nullable<sbyte> bim09 { get; set; }
        public Nullable<sbyte> bim10 { get; set; }
        public Nullable<sbyte> bim11 { get; set; }
        public Nullable<sbyte> bim12 { get; set; }
        public Nullable<sbyte> tri01 { get; set; }
        public Nullable<sbyte> tri02 { get; set; }
        public Nullable<sbyte> tri03 { get; set; }
        public Nullable<sbyte> tri04 { get; set; }
        public Nullable<sbyte> tri05 { get; set; }
        public Nullable<sbyte> tri06 { get; set; }
        public Nullable<sbyte> tri07 { get; set; }
        public Nullable<sbyte> tri08 { get; set; }
        public Nullable<sbyte> tri09 { get; set; }
        public Nullable<sbyte> tri10 { get; set; }
        public Nullable<sbyte> tri11 { get; set; }
        public Nullable<sbyte> tri12 { get; set; }
        public Nullable<sbyte> sem01 { get; set; }
        public Nullable<sbyte> sem02 { get; set; }
        public Nullable<sbyte> sem03 { get; set; }
        public Nullable<sbyte> sem04 { get; set; }
        public Nullable<sbyte> sem05 { get; set; }
        public Nullable<sbyte> sem06 { get; set; }
        public Nullable<sbyte> sem07 { get; set; }
        public Nullable<sbyte> sem08 { get; set; }
        public Nullable<sbyte> sem09 { get; set; }
        public Nullable<sbyte> sem10 { get; set; }
        public Nullable<sbyte> sem11 { get; set; }
        public Nullable<sbyte> sem12 { get; set; }
        public Nullable<sbyte> ano01 { get; set; }
        public Nullable<sbyte> ano02 { get; set; }
        public Nullable<sbyte> ano03 { get; set; }
        public Nullable<sbyte> ano04 { get; set; }
        public Nullable<sbyte> ano05 { get; set; }
        public Nullable<sbyte> ano06 { get; set; }
        public Nullable<sbyte> ano07 { get; set; }
        public Nullable<sbyte> ano08 { get; set; }
        public Nullable<sbyte> ano09 { get; set; }
        public Nullable<sbyte> ano10 { get; set; }
        public Nullable<sbyte> ano11 { get; set; }
        public Nullable<sbyte> ano12 { get; set; }
        public Nullable<short> anoFabricacao { get; set; }
        public string registroAnvisa { get; set; }
        public Nullable<System.DateTime> dataValidade { get; set; }
        public Nullable<System.DateTime> dataInstalacao { get; set; }
        public Nullable<sbyte> inativo { get; set; }
        public string obs { get; set; }
        public Nullable<decimal> mtbf { get; set; }
        public Nullable<decimal> mttr { get; set; }
        public Nullable<decimal> disponibilidade { get; set; }
        public Nullable<decimal> confiabilidade { get; set; }
        public Nullable<decimal> cpmv { get; set; }
        public Nullable<decimal> valorEquipamentoNovo { get; set; }
        public Nullable<decimal> taxaDepreciacaoFiscalAnual { get; set; }
        public Nullable<short> vidaUtilAnos { get; set; }
        public Nullable<decimal> depreciacaoFiscalMensal { get; set; }
        public Nullable<decimal> depreciacaoContabilMensal { get; set; }
    }
}
