//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cadastro
    {
        public long autonumero { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string endereco { get; set; }
        public Nullable<int> autonumeroSistema { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public string nomeSubSistema { get; set; }
        public Nullable<int> autonumeroLocalAtendido { get; set; }
        public string nomeLocalAtendido { get; set; }
        public Nullable<int> autonumeroLocalFisico { get; set; }
        public string nomeLocalFisico { get; set; }
        public Nullable<int> autonumeroEquipe { get; set; }
        public string nomeEquipe { get; set; }
        public Nullable<int> autonumeroSetor { get; set; }
        public string nomeSetor { get; set; }
        public Nullable<int> autonumeroPredio { get; set; }
        public string nomePredio { get; set; }
        public string serie { get; set; }
        public string modelo { get; set; }
        public string capacidade { get; set; }
        public string patrimonio { get; set; }
        public Nullable<int> diaUtil { get; set; }
        public Nullable<int> grupo { get; set; }
        public string fabricante { get; set; }
        public Nullable<System.DateTime> dataPrevista { get; set; }
        public Nullable<System.DateTime> dataCompra { get; set; }
        public Nullable<System.DateTime> dataGarantia { get; set; }
        public string cancelado { get; set; }
        public Nullable<int> periodicidade { get; set; }
        public string mesManuAno { get; set; }
        public string mesManuSem01 { get; set; }
        public string mesManuSem02 { get; set; }
        public string mesManuTri01 { get; set; }
        public string mesManuTri02 { get; set; }
        public string mesManuTri03 { get; set; }
        public string mesManuTri04 { get; set; }
        public string obsLocal { get; set; }
        public string mesManuSemestre { get; set; }
        public Nullable<long> contadorPmocEquipamento { get; set; }
    }
}
