//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_diarioplantao
    {
        public int autonumero { get; set; }
        public Nullable<long> autonumeroCliente { get; set; }
        public string siglaCliente { get; set; }
        public string url { get; set; }
        public string descricao { get; set; }
        public Nullable<long> autonumeroUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public Nullable<System.DateTime> dataDiario { get; set; }
    }
}
