//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_insumo
    {
        public int autonumero { get; set; }
        public string nome { get; set; }
        public string unidade { get; set; }
        public Nullable<double> preco { get; set; }
        public string codigo { get; set; }
        public string anoMes { get; set; }
        public string fonte { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
