//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_medicaoitens
    {
        public long autonumero { get; set; }
        public Nullable<long> autonumeroMedicao { get; set; }
        public string medicao { get; set; }
        public string etapa { get; set; }
        public string fonte { get; set; }
        public Nullable<long> autonumeroPlanilhaFechada { get; set; }
        public Nullable<long> item { get; set; }
        public string codigo { get; set; }
        public string nome { get; set; }
        public string unidade { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<decimal> qtdeContratada { get; set; }
        public Nullable<decimal> medicaoAtual { get; set; }
        public Nullable<decimal> qtdeTotalAcumulada { get; set; }
        public Nullable<decimal> estoque { get; set; }
        public Nullable<decimal> valorAposMedicao { get; set; }
        public string cancelado { get; set; }
    }
}
