//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_orcamento
    {
        public int autonumero { get; set; }
        public string codigoOrcamento { get; set; }
        public Nullable<long> autonumeroOs { get; set; }
        public string codigoOs { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string siglaCliente { get; set; }
        public string nomeCliente { get; set; }
        public Nullable<long> autonumeroUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public string cancelado { get; set; }
        public string nomeStatus { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string localObra { get; set; }
        public string descricao { get; set; }
    }
}
