//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ordemservico
    {
        public long autonumero { get; set; }
        public Nullable<long> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string sigla { get; set; }
        public string nomeUsuario { get; set; }
        public Nullable<System.DateTime> dataEmissao { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
        public string codigoOs { get; set; }
        public string cancelado { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<long> autonumeroSistema { get; set; }
        public string processo { get; set; }
        public string cap { get; set; }
        public string enderecoCliente { get; set; }
        public string solicitante { get; set; }
        public string nomeItem { get; set; }
        public string siglaItem { get; set; }
        public string resumoServico { get; set; }
        public Nullable<int> quantidadeSS { get; set; }
        public string situacao { get; set; }
        public string etapa { get; set; }
        public string medicao { get; set; }
        public string local { get; set; }
    }
}
