//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_os_itens
    {
        public long autonumero { get; set; }
        public string nome { get; set; }
        public string nomeFonte { get; set; }
        public string unidade { get; set; }
        public Nullable<decimal> quantidade { get; set; }
        public Nullable<decimal> precoUnitario { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> bdiServico { get; set; }
        public Nullable<decimal> bdiMaterial { get; set; }
        public Nullable<long> autonumeroOs { get; set; }
        public string codigoOs { get; set; }
        public Nullable<long> autonumeroUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string cancelado { get; set; }
        public string servico { get; set; }
        public Nullable<long> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public string codigoInsumoServico { get; set; }
        public string memoriaCalculo { get; set; }
        public string nomePF { get; set; }
        public Nullable<decimal> quantidadePF { get; set; }
        public Nullable<decimal> precoUnitarioPF { get; set; }
        public Nullable<decimal> totalPF { get; set; }
        public string nomeFontePF { get; set; }
        public Nullable<long> itemPF { get; set; }
        public string unidadePF { get; set; }
        public string codigoPF { get; set; }
        public string codigoOrdemServico { get; set; }
        public string etapa { get; set; }
        public string medicao { get; set; }
        public Nullable<short> qtdeMaoObra { get; set; }
    }
}
