//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_os
    {
        public int autonumero { get; set; }
        public string codigoOs { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string siglaCliente { get; set; }
        public string nomeCliente { get; set; }
        public Nullable<int> autonumeroSistema { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroSubSistema { get; set; }
        public string nomeSubSistema { get; set; }
        public Nullable<int> autonumeroPredio { get; set; }
        public string nomePredio { get; set; }
        public Nullable<int> autonumeroSetor { get; set; }
        public string nomeSetor { get; set; }
        public Nullable<int> autonumeroLocalFisico { get; set; }
        public string nomeLocalFisico { get; set; }
        public Nullable<int> autonumeroPrioridade { get; set; }
        public string nomePrioridade { get; set; }
        public Nullable<int> autonumeroUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public string matricula { get; set; }
        public Nullable<int> autonumeroServico { get; set; }
        public string nomeServico { get; set; }
        public string complemento { get; set; }
        public string ramal { get; set; }
        public Nullable<System.DateTime> dataSolicitacao { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public Nullable<System.DateTime> dataTermino { get; set; }
        public string prazoPrioridade { get; set; }
        public string descricao { get; set; }
        public string cancelado { get; set; }
        public string nomeStatus { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<double> bdiServico { get; set; }
        public Nullable<double> bdiMaterial { get; set; }
        public string codigoTabela { get; set; }
        public string nomeEquipe { get; set; }
        public Nullable<decimal> valorServico { get; set; }
        public Nullable<decimal> valorMaterial { get; set; }
        public string url { get; set; }
        public string url1 { get; set; }
        public Nullable<long> codigoEquipamento { get; set; }
        public Nullable<System.TimeSpan> totalHoras { get; set; }
        public string importadaCustoFixo { get; set; }
        public string codigoOrdemServico { get; set; }
        public string etapa { get; set; }
        public string medicao { get; set; }
        public string localAtendido { get; set; }
        public Nullable<int> autonumeroAutorizado { get; set; }
        public string nomeAutorizado { get; set; }
        public Nullable<sbyte> desabilitado { get; set; }
    }
}
