//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_os_acompanhamento
    {
        public long autonumero { get; set; }
        public string nome { get; set; }
        public Nullable<long> autonumeroOs { get; set; }
        public string codigoOs { get; set; }
        public Nullable<long> autonumeroUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string cancelado { get; set; }
        public Nullable<long> autonumeroCliente { get; set; }
        public string nomeCliente { get; set; }
        public Nullable<long> autonumeroEquipe { get; set; }
        public string nomeEquipe { get; set; }
        public string nomeStatus { get; set; }
    }
}
