//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_planilhafechada
    {
        public long autonumero { get; set; }
        public long autonumeroCliente { get; set; }
        public string fonte { get; set; }
        public long item { get; set; }
        public string codigo { get; set; }
        public string nome { get; set; }
        public string unidade { get; set; }
        public decimal qtdeContratada { get; set; }
        public decimal preco { get; set; }
        public decimal estoque { get; set; }
        public decimal qtdeCustoFixo { get; set; }
        public decimal qtdeUsada { get; set; }
    }
}
