//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_preventiva
    {
        public int cod_preventiva { get; set; }
        public Nullable<int> cod_centro_custo { get; set; }
        public Nullable<int> cod_sistema { get; set; }
        public Nullable<int> cod_subsistema { get; set; }
        public Nullable<int> cod_local_fisico { get; set; }
        public Nullable<int> cod_predio { get; set; }
        public Nullable<int> cod_setor { get; set; }
        public string andar { get; set; }
        public Nullable<int> dia_util { get; set; }
        public Nullable<int> cod_respons { get; set; }
        public Nullable<System.DateTime> data_prevista { get; set; }
        public Nullable<int> grupo { get; set; }
        public Nullable<int> cod_periodo { get; set; }
    }
}
