//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_subsistemacliente
    {
        public int autonumeroCliente { get; set; }
        public int autonumeroSubsistema { get; set; }
        public int autonumeroSistema { get; set; }
        public string nome { get; set; }
        public string nomeSistema { get; set; }
        public Nullable<int> autonumeroEquipe { get; set; }
        public string nomeEquipe { get; set; }
        public Nullable<int> qtdePorGrupoRelatorio { get; set; }
        public Nullable<int> qtdeAtendidaEquipePorDia { get; set; }
        public Nullable<int> autonumeroEquipe2 { get; set; }
        public string nomeEquipe2 { get; set; }
        public string anual { get; set; }
        public string semestre { get; set; }
        public string trimestre { get; set; }
        public Nullable<sbyte> chkTodoMes { get; set; }
        public string mesesParaCalcular { get; set; }
        public string bimestre { get; set; }
    }
}
