//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int autonumero { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string tipoUsuario { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string matricula { get; set; }
        public string cancelado { get; set; }
        public string cliente { get; set; }
        public Nullable<int> autonumeroTipoUsuario { get; set; }
    }
}
