//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apinovo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tramitacao
    {
        public int autonumero { get; set; }
        public Nullable<int> autonumeroGrupoTramitacao { get; set; }
        public string nomeGrupoTramitacao { get; set; }
        public string nomeCliente { get; set; }
        public string contrato { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string intervaloMedicao { get; set; }
        public Nullable<System.DateTime> ultimaTramitacao { get; set; }
        public string destino { get; set; }
        public string cancelado { get; set; }
        public Nullable<int> autonumeroCliente { get; set; }
        public string nroProcessoPagamento { get; set; }
    }
}
